### ISSUE TITLE
Objective JH-1: Better Image Management and Testing

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#16]
See also:

 - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/5

### Motivation

 - Smoother process to regularly update base images used for Hub environments
 - Catch regressions and issues with upstream libraries via automated tests

### Owner(s)
@batpad @yuvipanda @ranchodeluxe 

### Success criteria
 - [x] Cleanup veda-jh-environments repository to remove unused cruft - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/26
 - [x] Have automated tests setup with CI to test regressions with notebooks - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/27

**Comment by yuvipanda** [comment]
This is almost done, the tests have been merged. Needs a paragraph or so of docs to be called 'done'
