### ISSUE TITLE
Objective JH-2: Dynamic Image Building UI

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#17]
See also: 

 - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/6

### Motivation

 - Current UI when user logs into JupyterHub is non-intuitive
 - Do ground-work to overhaul existing kubespawner interface
 - Be able to integrate dynamic image building to allow users to flexibly specify environments
 - Don’t require users to understand building and pushing Docker images
 - Allow shareability of reproducible environment alongwith code

### Owner(s)

@batpad @oliverroick @yuvipanda 

### Success criteria

 - [x] Modernize and integrate jupyterhub-fancy-profiles to allow more complex frontend features to be built
 - [ ] Have new fancy-profiles integrated into production VEDA Hub
 - [ ] Document updates to kubespawner and how to use

### Stretch

- Stretch: Integrate dynamic image building UI, similar to mybinder.org

**Comment by yuvipanda** [comment]
Pretty happy to see this :)

Also hat tip to @arnim for funding most of this work this from GESIS so far! https://2i2c.org/blog/2024/jupyterhub-binderhub-gesis/ has some more information.

**Comment by yuvipanda** [comment]
We aren't going to do the stretch goal this quarter, but everything else can be done once https://github.com/NASA-IMPACT/veda-jupyterhub/issues/34 is done
