### ISSUE TITLE
Objective JH-3: Automatically pull GHG example notebooks

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#18]
See also: https://github.com/NASA-IMPACT/veda-jupyterhub/issues/7

### Motivation

 - Similar to the VEDA hub, we should give users example and starter notebooks when they sign-in to the hub
 - Do this in a way that’s easily configurable and transferrable to other hubs

### Owner(s)
@batpad @sunu @yuvipanda 

### Success criteria

 - [x] When a user logs into the GHG hub, they have the ghg-docs folder available to them, similar to current behaviour w/ `veda-docs` on the VEDA hub.
 - [x] The code is structured to be configurable and re-usable so we are not forking the init-container code that does this for the VEDA hub
 - [ ] Document open source library / announce to Jupyter community (attribute VEDA / NASA IMPACT!)

**Comment by batpad** [comment]
@j08lue this is implemented! Users should now get the `ghgc-docs` folder by default in their home directory when they login to the GHG Hub.

**Comment by yuvipanda** [comment]
@batpad I think this can be closed once you post to discourse.jupyter.org :)

**Comment by batpad** [comment]
> @batpad I think this can be closed once you post to discourse.jupyter.org :)

Yea, just waiting to close https://github.com/NASA-IMPACT/jupyterhub-gitpuller-init/issues/1 for some better docs and then we can post and close this!
