### ISSUE TITLE
Objective JH-4: Allow tiered access to JupyterHub resources

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#19]
See also: https://github.com/NASA-IMPACT/veda-jupyterhub/issues/8

### Motivation

 - We want to restrict the amount of resources available to some groups of users
 - Increase the amount of resources available to some groups of users
 - Explore a completely ephemeral hub with lower barrier to entry and smaller resource allocations, allowing broader sharing of reproducible analysis

### Owner(s)
@batpad @wildintellect @yuvipanda 

### Success criteria

 - [x] We have defined separate groups with access to different profiles
 - [ ] We have an ephemeral hub setup which has much lower login / approval requirements

**Comment by colliand** [comment]
FYI: I referred to this issue in today's VEDA call as a likely target for the next sprint. I did so with the caveat that I had not confirmed this timing with Yuvi and Sanjay.

**Comment by yuvipanda** [comment]
We have done this for the GHG hub, and we'll just turn on `auth_state` for VEDA hub but not actually differentiate users yet.
