### ISSUE TITLE
Objective JH-5: Improve QGIS experience inside Hub

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#20]
### See also:

 - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/2
 - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/9
 - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/12

### Motivation

 - We have a working demo of running QGIS inside the hub, but could do a lot to make the user experience more integrated
Improve the user experience of using QGIS in the hub, making it feel more seamless in the browser
 - Give access to NASA datasets by default, without the user having to worry about authentication when they are authenticated into the Hub
 - Improve the experience of using the QGIS STAC plugin
 - Ground-work to eventually allow users to open a dataset in QGIS from the VEDA UI

### Owner(s)

@batpad @geohacker @yuvipanda 

### Success criteria 

 - [x] Improved UI around the QGIS desktop environment to look more integrated with the Hub
 - [ ] QGIS is started with a default project file with preset data sources automatically added
 - [ ] We have some control over upstream development of the QGIS STAC plugin
 - [ ] Backend work to enable templatizing a project file to open it with query parameters supplied by the VEDA UI frontend

**Comment by yuvipanda** [comment]
I think we want to deploy the qgis jupyter plugin into the image and get that deployed, and then we can call this done.
