### ISSUE TITLE
Objective JH-6: Improve map visualization in notebooks

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#21]
See also:

 - https://github.com/NASA-IMPACT/veda-jupyterhub/issues/13

### Motivation

 - Current map visualization tools in Jupyter notebooks are well behind the state-of-the-art of modern browser based map tools
 - Visualizing on the map inside Jupyter is still an extremely fragmented experience with no clear way of doing things across use-cases
 - Still hard to combine raster and vector data seamlessly alongwith analysis
 - Hard limits on size of datasets for interactive map visualizations

### Owner(s)

@batpad @wildintellect @kylebarron 

### Success criteria

 - [ ] At least one demo of using lonboard / next-generation WASM + GPU-based mapping clients with NASA data
 - [x] A roadmap to collaborate with the larger community on supporting modern cloud-native data formats and improving GIS tooling within Jupyter notebooks

**Comment by wildintellect** [comment]
Need a better goal than that, or more specifics, we already have Lonboard examples in MAAP and VEDA https://github.com/MAAP-Project/maap-documentation-examples/blob/main/gedi-subset/notebooks/lonboard_exploration.ipynb

**Comment by batpad** [comment]
Lonboard continued to get more usage, and we were able to further support of sharing of notebooks that used lonboard on https://notebooksharing.space

@wildintellect would it be possible to compile some examples or even just make some brief notes on how `lonboard` has been especially useful - it seems like there were a few really good examples in the past few months of folks using `lonboard` for things that would not have been possible without it.

We've had some requests for features to add to lonboard, and we plan on spending some time in the coming quarter to add frontend features to improve usability.

**Comment by batpad** [comment]
On the Jupyter GIS front, we have continued to stay involved in discussions and being part of community meetings. It's great news that [QuantStack is taking the lead](https://blog.jupyter.org/jupytergis-d63b7adf9d0c) on developing a framework for collaborative GIS tooling within Jupyter. We will continue being involved, contribute where we can, and be well setup to deploy these tools to our users as they become available.

With the focus of the Jupyter GIS project being on collaborative editing and providing more "desktop-app" like experiences, we feel our work on `lonboard` dealing with rendering large-scale vector data and optimizing for cloud-native formats continues to be well aligned and complimentary work.

**Comment by batpad** [comment]
Some good examples of using `lonboard` in this past quarter for real-world usage + notebooksharing.space to share can be found in the examples in this repo: https://github.com/MAAP-Project/geotrees-demo/
