### ISSUE TITLE
Objective JH-9: Integrate the MAAP/JPL Data Processing Service (DPS) into VEDA JupyterHub

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#24]
### Motivation

 - Tracking usage
 - Auth
 - User experience - how users interact with DPS and how they find their results (no workspace-mounted bucket)

### Owner(s)

@batpad @wildintellect 

### Success Criteria

 - [x] Compare with workflows in MAAP ADE
 - [ ] Figure out how users retrieve their results

(@wildintellect @j08lue - I will need your help here to define exactly what success looks like here)

**Comment by wildintellect** [comment]
The repos are all in https://github.com/MAAP-Project/?q=jupyter&type=all&language=&sort= but from the screen shot I believe they are all in Pypi.

![image](https://github.com/NASA-IMPACT/veda-jupyterhub/assets/306179/3b21a975-84af-447f-afca-d7a0deee78dc)


From Slides https://docs.google.com/presentation/d/1TSJv111FVJCXD8EHfCTABVTbMCqUXMyTKyv67WLVoIk/edit#slide=id.g27123571c27_0_0

`algorithm` and `dps` might be the ones we need.

**Comment by batpad** [comment]
Thank you @wildintellect !

So, next steps:

Add the `maap-algorithms-jupyter-extension` and `maap-dps-jupyter-extension` packages to our image: https://github.com/NASA-IMPACT/pangeo-notebook-veda-image, get a test image, and test on the hub to see if we get the DPS UI in JupyterLab.

@sunu - I think I can go ahead and try this? I can reach out if I run into any issues.

**Comment by batpad** [comment]
I added the above `maap` lab extensions and built an image from this branch: https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/tree/test-maap-dps

The image has been pushed to ECR at `public.ecr.aws/nasa-veda/pangeo-notebook-veda-image:e39bf5ade122`

One can test running it on the hub by pasting the above image location into the "Bring Your Own Image" Custom Image field. 

@wildintellect I see the MAAP extensions show up in the JupyterLab Launcher interface -> Register Algorithm, Submit Jobs, and View Jobs

Let's try and catch up on next steps and what it would take to get an auth token and plug it in to test the functionality?

**Comment by wildintellect** [comment]
@ranchodeluxe has some experience borrowing a token from MAAP to submit jobs from inside VEDA.

**Comment by batpad** [comment]
Continues in https://github.com/NASA-IMPACT/veda-jupyterhub/issues/43

**Comment by ranchodeluxe** [comment]
This specfic tag `public.ecr.aws/nasa-veda/pangeo-notebook-veda-image:e39bf5ade122` is not being found and results in an image pull back-off error

I tried using the newest tag for that repo: `public.ecr.aws/nasa-veda/pangeo-notebook-veda-image:1b9438a4dd6f`

I can probably problem solve this myself but where cannot immediately find the GH repo for this image?

**Comment by ranchodeluxe** [comment]
(whoops, wrong ticket) 
next steps I will get to Friday is to build a new image using this extension: 

https://pypi.org/project/maap-jupyter-server-extension/

and then bake in  the `MAAP_PGT` token somehow
