### ISSUE TITLE
Manage qgis and nasa-singleuser images in a consistent fashion

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#26]
Part of [Objective 1](https://github.com/NASA-IMPACT/veda-jupyterhub/issues/16)

Currently, we manage the `nasa-qgis-image` here: https://github.com/2i2c-org/nasa-qgis-image

We manage the Pangeo derived `nasa-veda-singleuser` image as part of `veda-jh-environments` here: https://github.com/NASA-IMPACT/veda-jh-environments/tree/main/docker-images/custom/nasa-veda-singleuser

We are [no longer using](https://github.com/NASA-IMPACT/veda-jh-environments/pull/53) a lot of things in the `veda-jh-environments` repo. In the interest of simplicity, I propose managing each image in its own repository, and following a consistent pattern for tests, etc.

What this would involve:

Create a separate repository for `nasa-singleuser-image` or so (need to decide on the naming), make it inherit from `pangeo-notebook`, and follow the `repo2docker` repository template to add tests in a consistent fashion. Wire up CI to use the repo2docker github action to run tests, and push the image to the container registry.

cc @yuvipanda

**Comment by yuvipanda** [comment]
https://docs.2i2c.org/how-to-guides/add-packages-to-image/ may be helpful documentation to follow :)

**Comment by sunu** [comment]
> https://docs.2i2c.org/how-to-guides/add-packages-to-image/ may be helpful documentation to follow :)

@yuvipanda the link returns a 404 page unfortunately

**Comment by batpad** [comment]
@sunu I think this seems similar as a how-to: https://docs.2i2c.org/admin/howto/environment/customize-image/

**Comment by batpad** [comment]
We've switched over the singleuser image to using a single repository using the `repo2docker` action, so with a similar setup to the nasa-qgis-image repository here: https://github.com/nasa-IMPACT/pangeo-notebook-veda-image/

We can consider moving the https://github.com/2i2c-org/nasa-qgis-image repo under the NASA-IMPACT org.

This all also needs better documentation, covered in https://github.com/NASA-IMPACT/veda-jupyterhub/issues/39

Going to close this.
