### ISSUE TITLE
Add different resource options for workshop

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#32]
From email from Sourish - for their workshop, they'd like to have the option of machines with more CPU and less RAM. The desired options are:

 - 8 cores/16 GB
 - 12 cores/16 GB
 - 8 cores/24 GB
 - 12 cores/24 GB

I'm just confirming which hub we should add these to.

@yuvipanda do you see any issues adding this to the profile / resource options?

cc @slesaad @sunu

**Comment by slesaad** [comment]
@batpad This would be for the GHG hub for now. We can extent it to other hubs if we see the need later.

**Comment by batpad** [comment]
@yuvipanda - unfortunately, getting an error after we merged the new resource options. Starting a server with any of the new options fails with:

<img width="649" alt="Screenshot 2024-05-09 at 12 11 51 AM" src="https://github.com/NASA-IMPACT/veda-jupyterhub/assets/72280/1cdf2366-a4ce-439b-b463-18dd9a33c535">

It fails immediately - the instance type is specified as `r5.4xlarge` which should have 16 VCPUs which **should** be enough but not sure if there's some weird placement issues? Would you be able to check logs or so or tell me where I could look?

Thank you!

**Comment by batpad** [comment]
This is done and should all work now.

**Comment by batpad** [comment]
Re-opening this for the follow-up:

From speaking to Sourish and them testing out the resource options we deployed: the workloads are CPU constrained, and they would like machines with 12-16CPUs. RAM is less important and would be fine with 16GB RAM.

Since the "compute-optimized" ec2 instances on AWS provide CPU:GB of RAM in a 1:2 ratio, it makes sense to give that additional RAM to users. Further, speaking to @yuvipanda about what node sizes, etc. would be optimal, we feel that having "1 node per user" is probably ideal and keeps things simple. So the plan is to use `c5.4xlarge` instances with 16 CPU and 32GB RAM. Leaving some head-room on the machines for system processes, etc. we can likely allocate 14CPU + 28GB RAM for user container.

Additionally, Sourish expressed a desire to have custom Python (Pangeo) and R images for the workshop, with additional packages installed onto the base system to save time and potential problems installing packages, etc.

Next steps here:

 - [x] Create a new node-pool for `c5.4xlarge` instances: https://github.com/2i2c-org/infrastructure/blob/main/eksctl/nasa-ghg.jsonnet#L30
 - [x] Create 2 new Profile Options for GHG center for the workshop for Python and R respectively, that don't give users too many options: i.e. have a fixed resource allocation of 14CPU + 28GB RAM and the Python and R images we create (for now they can point to the current Pangeo and R images we use)
 - [x] Create a new Github group for the workshop and add workshop admins and users to that group. cc @slesaad I'll email Sourish about this as well - do you know the best way to coordinate this?
 - [x] Give permissions to the 2 new profile options we create only to the workshop group, so these options don't show up for other / regular users AND so that workshop users don't have access to the existing profile options.

I'll follow up on email about creating the github group for the workshop. Once we have the list of packages they want for the custom images, I'll ticket that image creation separately.

cc @sunu

**Comment by batpad** [comment]
This was all done!
