### ISSUE TITLE
Grant access to "CASI-LIS-Dashboard" github org to VEDA hub

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#36]
As per email from Jessica M. Erlingis, there's a request to add the `CASI-LIS-Dashboard` Github org to have access to the VEDA hub.

I'm not sure if it works to add the whole org or if we need them to create a team and then we add `org`:`team`, but I can create a PR to add the org and then work through on the PR

cc @yuvipanda @slesaad

**Comment by yuvipanda** [comment]
ideally it would be a team, rather than a whole org. This is because `allowed_teams` in profile_list only allows for teams (not orgs), and we want to add that in the future.

**Comment by batpad** [comment]
Yup, that makes sense. So the team to be added is `dev-veda-jupyterhub` within the `CASI-LIS-Dashboard` org (thanks @slesaad for coordinating that!). I'll go ahead and make that PR.

@yuvipanda are there instructions we need to give them to do the "Grant" stuff on Github the first time they sign in as the org?

**Comment by batpad** [comment]
I think this is all done?

Thanks much @slesaad for figuring this all out and making sure it worked!
