### ISSUE TITLE
VEDA EJ Workshop Hub  

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-jupyterhub#37]
VEDA will be participating in an environmental justice (EJ) workshop at ESIP on July 23, 2024. After introducing and demoing the VEDA infrastructure participants will be prompted to enter the VEDA JH environment to run the following notebooks: 
- [Urban Heat Stress](https://gist.github.com/acblackford/ea3d069fd874b4485e1decc1201e5711) and
- [EJ Landfill](https://gist.github.com/WeathermanTrent/d461869759c1cd71bc768c0c6847f46a)
- _potentially_ [Houston_ AOD](https://gist.github.com/WeathermanTrent/744a6dc63cdd9e49621e010991a813ce) 

Sanjay and I met this morning and started talking on:
- User access (how do we provision access to users, manage, etc.)
- Future workshop-specific GH environments
- Resources needed

Creating this ticket to track the effort and conversations related to VEDA EJ Workshop Hub use.

**Comment by jerikac** [comment]
Adding to this ticket - other tasks that need tracking related to the EJ workshops include:
- [ ] prepping the Jupyter notebooks - ensure notebooks are ready for use 
> - [ ] Data for landfill notebook is reduced to only what is needed to lower data volumes
> - [ ] @WeathermanTrent only load data over the counties of interest rather than the entire state of Texas
> - [ ] data for landfill notebook is available in S3 --**or**-- data is available in a shared folder that is preloaded into workshop hub environment/shared with users at the workshop
> - [ ] Data for heat stress notebook is reduced to only what is needed to lower data volumes
> - [ ] data for heat stress notebook is available in S3 --**or** -- data is available in a shared folder that is preloaded into workshop hub environment/shared with users at the workshop
 - [ ] notebooks have been reviewed for clarity and efficiency

**Comment by batpad** [comment]
@jerikac will we be creating a separate Github org or team for the event?

It would be nice to define that team soon so that we can add permissions to the hub for that group accordingly and test that all works well.

**Comment by jerikac** [comment]
Yes. I'm out of the loop on the process - not sure if we have a GitHub group specifically for workshops that gets recycled or if we need to create something new. I've started collecting GitHub usernames from attendees, so once things are ready we can add them before the workshop (we can add on July 22, workshop on July 23).

What do you information do you need in order to start defining the team? In terms of permissions, users are just going to be running the notebooks (is that read?), and then if I and @smk0033 can have admin privileges for the GitHub team that'd be awesome.

**Comment by batpad** [comment]
We should probably create a team for this workshop under the `nasa-veda-workshops` Github organization: https://github.com/nasa-veda-workshops

@slesaad @brianmfreitag - I'm not admin on that Github org - would one of you be able to create a team for this workshop and make @jerikac and @smk0033 admins so they can add people? And if you give me the name of the team created, I can add give it permissions to the hub.

**Comment by batpad** [comment]
Thanks to @slesaad for creating a group called `veda-ej-workshop-esip-2024` under the `nasa-veda-workshops` github org. @smk0033 @jerikac you both should have admin permissions to add users to this group - I think @slesaad should be able to help in case you run into issues.

All users in that group will get access to the VEDA hub as soon as https://github.com/2i2c-org/infrastructure/pull/4428 is merged. And we can cleanup / remove access once the workshop is over.

**Comment by jerikac** [comment]
I've created a repo specific to the ESIP workshops for the notebooks (@smk0033 @WeathermanTrent ): https://github.com/nasa-veda-workshops/esip-2024 . 

@WeathermanTrent  & @acblackford the notebooks need to be pushed to the repo above in order for workshop attendees to access them in the Hub. 

**Once added to the GitHub Team users will need to follow [THIS LINK](https://hub.openveda.cloud/hub/user-redirect/git-pull?repo=https://github.com/nasa-veda-workshops/esip-2024&urlpath=lab/tree/esip-2024/&branch=main) in order to clone the repo containing the notebooks into their hub environment**

Also tested adding a member to the GitHub team and confirmed they were able to access the Hub after being added.
