### ISSUE TITLE
VEDA EJ Workshop Hub Clean Up

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-jupyterhub#38]
Ticket to remind the team to remove access and perform any clean-up tasks after the VEDA EJ Workshop in July. 

- [x] revoke hub access for workshop participants 1-week after workshop
- [x] restore hub environment (if applicable) 
- [ ] collect lessons learned

**Comment by jerikac** [comment]
We advertised 10-days of access post-workshop, so we should aim to clean the EJ Workshop Hub up on August 2nd, if that's okay?

**Comment by batpad** [comment]
Made a PR to remove access to the group created for the EJ workshop: https://github.com/2i2c-org/infrastructure/pull/4569/files

**Comment by batpad** [comment]
@jerikac leaving this open to collect "lessons learned" and any feedback / things that could maybe have been improved. Curious to know how it all went!
