### ISSUE TITLE
Objective JH-1: Enforce home directory quotas per-user

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#41]
## Motivation 

User home directories are meant to store code and notebooks, with data being stored in object storage if possible. They are mounted via NFS, and currently can grow unbounded. The unboundedness can cause cloud cost problems (unlike memory / CPU, which are bounded inherently), as well as encourage coding patterns that are not cloud optimized (like downloading a TB of .nc files to home directory before working on them). 

## Proposal

We will enforce home directory storage quotas for each user, as well as an overall fixed size for the entire hub. This will require migrating from the existing AWS EFS based setup to running an in-cluster NFS server with XFS based projectquota.

## Owners
 - @yuvipanda  (2i2c)
 - @batpad  (Development Seed)
 - @sunu (Development Seed)
  
## Success Criteria
 - [ ] Users can not use more than their allowed quota of home directory space
 - [ ] Migration to this new home directory set up is completed for at least one hub (hub.openveda.io to start)

**Comment by batpad** [comment]
@yuvipanda are you able to outline a little bit here what steps would be, and give me and @sunu some reading to get started?

And then we should probably get on a call early next week to kick this off.

Thanks!

**Comment by yuvipanda** [comment]
yes let's do a call soon to kick this off!

Here's some prior reading that may be useful for @sunu!

- https://github.com/pangeo-data/pangeo-cloud-federation/issues/654 is where a lot of prior discussion about this feature happened. Basically, us doing this work is (in my head) completion of that work. Reading up on that issue may help!
- We'll be creating a new helm chart, which will primarily provide the following two items:
  - a userspace NFS server, https://github.com/nfs-ganesha/nfs-ganesha, serving from a PVC attached to a deployment
  - A sidecar in the same deployment running https://github.com/yuvipanda/get-quota-your-home/ so it sets quotas appropriately on the same disk that the NFS server is running from
- We will need to write at least a little integration test for this helm chart

I hope that's a useful start, @sunu!

@batpad how do we schedule this?

**Comment by sunu** [comment]
Thanks @yuvipanda! This is very useful. I'll give those threads a read.

**Comment by sunu** [comment]
Here's an update on the progress on this issue so far:
- I have set up a repo at https://github.com/sunu/jupyter-home-nfs and created CI workflow to build and publish docker images for the latest NFS Ganesha version
- I have created some [example k8s manifests](https://github.com/sunu/jupyter-home-nfs/tree/main/example) to test the workflow end-to-end with https://github.com/yuvipanda/get-quota-your-home
- So far, everything works pretty well.
  - storage quota is enforced effectively. Here's an example of enforcing a 1MB quota:
    ```bash
    $ kubectl exec -it -n nfs-test nfs-client -- sh
    / # 
    / # dd if=/dev/zero of=1mb.bin bs=1M count=1
    1+0 records in
    1+0 records out
    1048576 bytes (1.0MB) copied, 0.002145 seconds, 466.2MB/s
    / # dd if=/dev/zero of=2mb.bin bs=1M count=2
    2+0 records in
    2+0 records out
    2097152 bytes (2.0MB) copied, 0.002712 seconds, 737.5MB/s
    / # cp 1mb.bin /data/
    / # cp 2mb.bin /data/
    cp: can't create '/data/2mb.bin': No space left on device
    ```
  - User files are retained after deleting and re-creating the cluster as long as we use a pre-provisioned disk

cc @batpad @yuvipanda

**Comment by yuvipanda** [comment]
@sunu AMAZING! This looks great, continue on! I'd like more comments in https://github.com/sunu/jupyter-home-nfs/blob/main/nfs-ganesha/start.sh but otherwise awesome job!

Use https://github.com/jupyterhub/chartpress for CI and packaging. You can also git merge the get-quota-the-home repo into your repo (preserving history) to make this process easier too.

Excited to see this go!

**Comment by batpad** [comment]
This is moving along really nicely and progress can be tracked here: https://github.com/2i2c-org/infrastructure/issues/4647

This should be on track to be able to do a full test on staging, ideally by end of this week.

**Comment by Gman0909** [comment]
Should this be closed now the tracked issue is complete?
