### ISSUE TITLE
Objective JH-7: Ephemeral Public Access Hub

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#47]
## Motivation

[mybinder.org](https://mybinder.org) has been a phenomenal success in making interactive computation accessible to large swathes of folks. By simply clicking a link, without any login requirements, end users (and lay people) can explore computational narratives and notebooks, with environments (and contents) dynamically built as needed. It would be useful to experiment with a VEDA adjacent ephemeral instance.

## Proposal

Deploy a mybinder.org-like public access (no authentication required) ephemeral hub (no persistent storage) with capped usage control (capped via total max amount of nodes available to be used at any given time).

## Owner(s)

 - @yuvipanda (2i2c)

## Success Criteria

 - [x] Ephemeral hub is set up at a particular URL
 - [x] Total number of nodes that can be spun up for this is kept low
 - [ ] Use cases for narrative storytelling with this public instance are explored

**Comment by batpad** [comment]
@yuvipanda - can we come up with a list of decisions that need to be made / questions that need answering here for us to proceed?

I'll start, but perhaps there's also a good check-list or so from the 2i2c side that we can work with @wildintellect to get filled / questions answered by the appropriate people.

 - What should be the max amount of compute / memory we want to provide simultaneously? This would be a derivative of the max cap for infrastructure spend for this hub.
 - For login, would we prefer:
    - No login at all
    - CI Logon or similar to have some login so we can do some user / usage tracking, but don't require further manual approvals
    - Other?

@yuvipanda I think if we can compile a list of questions that we would need specific answers for to go ahead with the ephemeral hub setup, @wildintellect can help us get answers so that we can go ahead here.

**Comment by wildintellect** [comment]
Requested timeline is to have this feature available before AGU in December. CC: @freitagb

**Comment by yuvipanda** [comment]
As a step 1, @batpad can you create an issue patterned around https://github.com/2i2c-org/infrastructure/issues/4246 (a template of sorts we use for new deployments like this) in the infrastructure repo? 


I would say we start this with no login at all, and *begin* by capping this to max of 1 r5.xlarge node only (and we can go from there). Once you fill out the template there, i can add additional info about this node cap.

**Comment by smarru** [comment]
@yuvipanda whats your experience with mybinder on keeping the auth open with no login at all. Does it attract any intentional or unintentional abuse?

**Comment by yuvipanda** [comment]
@smarru https://github.com/cryptnono/cryptnono was the result of our experience handling mybinder.org. cryptomining is the primary negative problem, and cryptnono has helped address that reasonably effectively.

**Comment by wildintellect** [comment]
Do we plan to set a time limit?

**Comment by yuvipanda** [comment]
@wildintellect there's an idle timeout time limit already, and we can also set a 'max' timelimit of maybe 12h?

**Comment by yuvipanda** [comment]
@wildintellect you can check out https://binder.opensci.2i2c.cloud/ to see how this would look like.

**Comment by yuvipanda** [comment]
Scheduled to be set up in https://github.com/2i2c-org/infrastructure/issues/4576

**Comment by yuvipanda** [comment]
Has been set up at binder.openveda.cloud!

**Comment by batpad** [comment]
Re-opening the issue until end of PI:

This is done! But we have not done much publicity or documentation around it. @brianmfreitag @yuvipanda - now that we have this, would be great to discuss what we can do / make people aware, and discuss use-cases that we want out of this.
