### ISSUE TITLE
Image management for VEDA, GHG and ESDIS Hubs

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#5]
Breaking off from https://github.com/2i2c-org/infrastructure/issues/3685

We need to clearly define who is responsible for image management for VEDA, GHG and ESDIS hubs. From the issue above:

```
This issue is to track and codify answers to the following questions:

    Where do requests for changes to the image go?
    Who is responsible for evaluating and making those changes?
    Who is responsible for periodic image updates (bumping up base image tag versions mostly)? And testing them?
    Who is responsible for updating the image tag used in the JupyterHub config?
```

Currently, images are managed in https://github.com/NASA-IMPACT/veda-jh-environments . Updating the default and base images on the hub involves making a change / PR to https://github.com/2i2c-org/infrastructure/blob/2a17dfb1d0fc2cfc5d6202cd2af582e090fdabce/config/clusters/nasa-veda/common.values.yaml#L70 and then needs 2i2c to merge and deploy the changes.

This is likely fine, but we need a well defined streamlined process for image management and clear responsibilities for who needs to keep them up-to-date, etc.

cc @yuvipanda @ranchodeluxe @wildintellect

**Comment by wildintellect** [comment]
Also noting that we are currently investigation automated testing of images before deployment to ensure core libraries are consistently usable. 
- https://github.com/NASA-IMPACT/veda-jh-environments/issues/44
- https://github.com/NASA-IMPACT/veda-jh-environments/issues/45

**Comment by batpad** [comment]
+cc @weiji14

**Comment by batpad** [comment]
We have image management a bit simplified and have added some basic tests.

It should now be much easier to update images, add packages, etc. with a reasonable degree of confidence.

We do need to document all of this better and deprecate the https://github.com/NASA-IMPACT/veda-jh-environments/ repository. There's a separate issue for that here: https://github.com/NASA-IMPACT/veda-jupyterhub/issues/39

We will include in the docs who is responsible for what, etc.

Closing this.
