### ISSUE TITLE
Update QGIS STAC plugin connection urls

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-jupyterhub#52]
## Description
The STAC catalog URLs for both VEDA and US GHG Center have been updated. The STAC API plugin in QGIS on Linux Desktop server still points to the old URLs.

They need to be updated to the following:
VEDA: https://openveda.cloud/api/stac
GHG: https://earth.gov/ghgcenter/api/stac/

### Acceptance Criteria:

- [ ] The STAC connection in QGIS in the hub point to correct urls

## Checklist:

- [ ] Epic Link
- [x] Detailed description
- [ ] Concept diagrams
- [ ] Assignee

**Comment by batpad** [comment]
The quickest way to do this would be:

 - [x] Make the required updates to the fork of the QGIS STAC plugin we are using, I'm guessing in this file: https://github.com/slesaad/qgis-stac-plugin/blob/support_gdal_assets/src/qgis_stac/definitions/catalog.py#L8
 - [x] Make a new release of our fork of the QGIS STAC plugin
 - [x] Use the updated version of the STAC plugin in our QGIS image: https://github.com/2i2c-org/nasa-qgis-image/blob/main/setup-qgis-plugins.bash#L10

@slesaad would you be able to make changes to your fork, and we can work on including the updated version on the default QGIS image on the hub

cc @sunu @yuvipanda

**Comment by batpad** [comment]
@slesaad just following up here .. would you be able to make the URL updates to your fork of the plugin and then we can work on updating the QGIS image on the hub? Thanks!

**Comment by slesaad** [comment]
sorry @batpad, this slipped my mind. I just made a PR to the repo here - https://github.com/slesaad/qgis-stac-plugin/pull/6
I've also invited you as a collaborator to the repository.

**Comment by batpad** [comment]
Thanks for making the updates @slesaad !

I created a new image which should include your changes: `quay.io/2i2c/nasa-qgis-image:0e8292b267b0`

Am just going to give it a try on the hub, will be great if you can give it a quick test as well, and if all looks good, I'll update the default QGIS image on the hubs.

Thanks again!

**Comment by batpad** [comment]
Unfortunately, this seems like it might be a bit of a rabbit-hole. The plugin is failing to install with an error like this:

<img width="492" alt="Screenshot 2024-08-09 at 2 05 53 PM" src="https://github.com/user-attachments/assets/16ef79c3-94d0-4021-b537-3976d135fc2d">

Ideally, nothing that @slesaad changed with the URL configs of the catalog should have affected this, but my hunch is some versions of things are not being pinned properly, and some upstream version changes have caused this. There's some libraries like `pydantic` that are vendored into the plugin code-base like so: https://github.com/slesaad/qgis-stac-plugin/tree/support_gdal_assets/src/qgis_stac/lib/pydantic that's making it a bit harder for me to think about debugging this.

I do see there have been some small updates to the plugin recently, one option maybe to try and catch-up to upstream and give it a go, but it doesn't seem like any of those changes are relevant to what we're facing.

Am figuring out a good environment locally to debug this. @sunu would really appreciate it if you have some time and we can look together. +cc @geohacker

**Comment by sunu** [comment]
Here's the full traceback for context:
```
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details. For further information visit https://errors.pydantic.dev/2.7/u/import-error 
Traceback (most recent call last):
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/__init__.py", line 41, in classFactory
    from .main import QgisStac
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/main.py", line 23, in 
    from .gui.qgis_stac_widget import QgisStacWidget
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/gui/qgis_stac_widget.py", line 31, in 
    from ..gui.connection_dialog import ConnectionDialog
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/gui/connection_dialog.py", line 26, in 
    from ..api.client import Client
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/api/client.py", line 9, in 
    from .base import BaseClient
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/api/base.py", line 28, in 
    from .network import ContentFetcherTask, NetworkFetcher
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/api/network.py", line 45, in 
    from ..lib import planetary_computer as pc
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/lib/planetary_computer/__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/lib/planetary_computer/__init__.py", line 4, in 
    from planetary_computer.sas import (
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/lib/planetary_computer/sas.py", line 14, in 
    from planetary_computer.settings import Settings
  File "/opt/conda/share/qgis/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/share/qgis/python/plugins/qgis_stac/lib/planetary_computer/settings.py", line 11, in 
    class Settings(pydantic.BaseSettings):
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/__init__.py", line 386, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.7/u/import-error


Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:53:30) [GCC 12.3.0] 
QGIS version: 3.38.1-Grenoble Grenoble, exported 

Python Path:
/opt/conda/share/qgis/python
/home/jovyan/.local/share/QGIS/QGIS3/profiles/default/python
/home/jovyan/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/opt/conda/share/qgis/python/plugins
/opt/conda/share/qgis/python/plugins
/opt/conda/share/qgis/python
/home/jovyan
/opt/conda/lib/python311.zip
/opt/conda/lib/python3.11
/opt/conda/lib/python3.11/lib-dynload
/opt/conda/lib/python3.11/site-packages
/home/jovyan/.local/share/QGIS/QGIS3/profiles/default/python
/opt/conda/share/qgis/python/plugins/qgis_stac/lib
```

**Comment by batpad** [comment]
Thanks @sunu for helping figure this out.

We've created a new image: `quay.io/2i2c/nasa-qgis-image:d76118ea0c15`

Am just going to test it out on the hub.

**Comment by batpad** [comment]
Hmm .. so with this updated image, the STAC plugin seems to work again. BUT, I'm some-how still getting the old URLs for the VEDA and GHG STAC catalogs.

Which is very strange because if I navigate to `/opt/conda/share/qgis/python/plugins/qgis_stac/definitions` on the container, the `catalog.py` looks correctly updated to the new values.

I'm not sure if QGIS is caching the STAC URLs somewhere, or what's going on really :( - @slesaad are you able to test with `quay.io/2i2c/nasa-qgis-image:d76118ea0c15` when you get online?

cc @sunu

**Comment by batpad** [comment]
Okay, so this is some cache in my home directory or so that's being persisted.

If I try the `quay.io/2i2c/nasa-qgis-image:d76118ea0c15` image on a "fresh" hub, the URLs seem to be updated correctly.

@slesaad once you're able to test, I think we can update the image in the 2i2c infrastructure repository.

cc @sunu

**Comment by batpad** [comment]
So it seems like QGIS persists some state in `~/.local/share/QGIS/` which was preventing it from reading the updated config and it was continuing to use the old configuration because of this state persisted in the home folder.

First, we tried to use the QGIS plugin `Plugin Reloader` to "reload" the qgis_stac plugin to get the new config reflected, but that didn't work. In the end, blowing away the `~/.local/share/QGIS/` folder did the trick and the STAC plugin was updated with the new URLs and seemed to work.

I hope this home directory cache issue does not affect a significant amount of users - we may need to keep an eye out and guide them through clearing out the older plugin config - I'm not sure if there's any other "cleaner" way to force the plugin to reload the config data.

@slesaad I think we're good to push this image out - will wait for your confirmation / thumbs-up before making the PR to the 2i2c infrastructure repository.

**Comment by slesaad** [comment]
Same experience, had to delete `~/.local/share/QGIS` to get the updated URLs. Should be good to go :)

**Comment by batpad** [comment]
This has been deployed to the VEDA hub. The updated QGIS image will now have the correct STAC endpoint URLs configured for the QGIS STAC plugin.

I came here to close the ticket, but realized I should probably also update the GHG and ESDIS hubs with the updated QGIS image? I'll close this once those are done.

**Comment by yuvipanda** [comment]
I think the actual error message is now surfaced in https://github.com/2i2c-org/nasa-qgis-image/actions/runs/10410081811/job/28831098729. The previous mechanism, of multiple `pip` or `conda` installs, was screwing up some earlier dependencies.
